// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: proto/echo_trace.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vector2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector2) Reset() {
	*x = Vector2{}
	mi := &file_proto_echo_trace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector2) ProtoMessage() {}

func (x *Vector2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector2.ProtoReflect.Descriptor instead.
func (*Vector2) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{0}
}

func (x *Vector2) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector2) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MaxUses       int32                  `protobuf:"varint,4,opt,name=max_uses,json=maxUses,proto3" json:"max_uses,omitempty"`
	UsesLeft      int32                  `protobuf:"varint,5,opt,name=uses_left,json=usesLeft,proto3" json:"uses_left,omitempty"`
	Weight        float64                `protobuf:"fixed64,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Tier          int32                  `protobuf:"varint,7,opt,name=tier,proto3" json:"tier,omitempty"`
	Value         int32                  `protobuf:"varint,8,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_echo_trace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetMaxUses() int32 {
	if x != nil {
		return x.MaxUses
	}
	return 0
}

func (x *Item) GetUsesLeft() int32 {
	if x != nil {
		return x.UsesLeft
	}
	return 0
}

func (x *Item) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Item) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *Item) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MoveInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           *Vector2               `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	LookDir       *Vector2               `protobuf:"bytes,2,opt,name=look_dir,json=lookDir,proto3" json:"look_dir,omitempty"`
	HasLookDir    bool                   `protobuf:"varint,3,opt,name=has_look_dir,json=hasLookDir,proto3" json:"has_look_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveInput) Reset() {
	*x = MoveInput{}
	mi := &file_proto_echo_trace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveInput) ProtoMessage() {}

func (x *MoveInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveInput.ProtoReflect.Descriptor instead.
func (*MoveInput) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{2}
}

func (x *MoveInput) GetDir() *Vector2 {
	if x != nil {
		return x.Dir
	}
	return nil
}

func (x *MoveInput) GetLookDir() *Vector2 {
	if x != nil {
		return x.LookDir
	}
	return nil
}

func (x *MoveInput) GetHasLookDir() bool {
	if x != nil {
		return x.HasLookDir
	}
	return false
}

type UseItemInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotIndex     int32                  `protobuf:"varint,1,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseItemInput) Reset() {
	*x = UseItemInput{}
	mi := &file_proto_echo_trace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseItemInput) ProtoMessage() {}

func (x *UseItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseItemInput.ProtoReflect.Descriptor instead.
func (*UseItemInput) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{3}
}

func (x *UseItemInput) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

type DropInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotIndex     int32                  `protobuf:"varint,1,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropInput) Reset() {
	*x = DropInput{}
	mi := &file_proto_echo_trace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropInput) ProtoMessage() {}

func (x *DropInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropInput.ProtoReflect.Descriptor instead.
func (*DropInput) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{4}
}

func (x *DropInput) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

type BuyInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyInput) Reset() {
	*x = BuyInput{}
	mi := &file_proto_echo_trace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyInput) ProtoMessage() {}

func (x *BuyInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyInput.ProtoReflect.Descriptor instead.
func (*BuyInput) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{5}
}

func (x *BuyInput) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type SellInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SlotIndex     int32                  `protobuf:"varint,1,opt,name=slot_index,json=slotIndex,proto3" json:"slot_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellInput) Reset() {
	*x = SellInput{}
	mi := &file_proto_echo_trace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellInput) ProtoMessage() {}

func (x *SellInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellInput.ProtoReflect.Descriptor instead.
func (*SellInput) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{6}
}

func (x *SellInput) GetSlotIndex() int32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

type TacticInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tactic        string                 `protobuf:"bytes,1,opt,name=tactic,proto3" json:"tactic,omitempty"` // RECON, DEFENSE, TRAP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TacticInput) Reset() {
	*x = TacticInput{}
	mi := &file_proto_echo_trace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TacticInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TacticInput) ProtoMessage() {}

func (x *TacticInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TacticInput.ProtoReflect.Descriptor instead.
func (*TacticInput) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{7}
}

func (x *TacticInput) GetTactic() string {
	if x != nil {
		return x.Tactic
	}
	return ""
}

// Generic C2S payload
type C2SMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*C2SMessage_Move
	//	*C2SMessage_UseItem
	//	*C2SMessage_Interact
	//	*C2SMessage_Pickup
	//	*C2SMessage_Drop
	//	*C2SMessage_Tactic
	//	*C2SMessage_Buy
	//	*C2SMessage_Sell
	//	*C2SMessage_ShopRefresh
	//	*C2SMessage_Fire
	//	*C2SMessage_DevSkip
	Payload       isC2SMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *C2SMessage) Reset() {
	*x = C2SMessage{}
	mi := &file_proto_echo_trace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *C2SMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C2SMessage) ProtoMessage() {}

func (x *C2SMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C2SMessage.ProtoReflect.Descriptor instead.
func (*C2SMessage) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{8}
}

func (x *C2SMessage) GetPayload() isC2SMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *C2SMessage) GetMove() *MoveInput {
	if x != nil {
		if x, ok := x.Payload.(*C2SMessage_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *C2SMessage) GetUseItem() *UseItemInput {
	if x != nil {
		if x, ok := x.Payload.(*C2SMessage_UseItem); ok {
			return x.UseItem
		}
	}
	return nil
}

func (x *C2SMessage) GetInteract() bool {
	if x != nil {
		if x, ok := x.Payload.(*C2SMessage_Interact); ok {
			return x.Interact
		}
	}
	return false
}

func (x *C2SMessage) GetPickup() bool {
	if x != nil {
		if x, ok := x.Payload.(*C2SMessage_Pickup); ok {
			return x.Pickup
		}
	}
	return false
}

func (x *C2SMessage) GetDrop() *DropInput {
	if x != nil {
		if x, ok := x.Payload.(*C2SMessage_Drop); ok {
			return x.Drop
		}
	}
	return nil
}

func (x *C2SMessage) GetTactic() *TacticInput {
	if x != nil {
		if x, ok := x.Payload.(*C2SMessage_Tactic); ok {
			return x.Tactic
		}
	}
	return nil
}

func (x *C2SMessage) GetBuy() *BuyInput {
	if x != nil {
		if x, ok := x.Payload.(*C2SMessage_Buy); ok {
			return x.Buy
		}
	}
	return nil
}

func (x *C2SMessage) GetSell() *SellInput {
	if x != nil {
		if x, ok := x.Payload.(*C2SMessage_Sell); ok {
			return x.Sell
		}
	}
	return nil
}

func (x *C2SMessage) GetShopRefresh() bool {
	if x != nil {
		if x, ok := x.Payload.(*C2SMessage_ShopRefresh); ok {
			return x.ShopRefresh
		}
	}
	return false
}

func (x *C2SMessage) GetFire() bool {
	if x != nil {
		if x, ok := x.Payload.(*C2SMessage_Fire); ok {
			return x.Fire
		}
	}
	return false
}

func (x *C2SMessage) GetDevSkip() bool {
	if x != nil {
		if x, ok := x.Payload.(*C2SMessage_DevSkip); ok {
			return x.DevSkip
		}
	}
	return false
}

type isC2SMessage_Payload interface {
	isC2SMessage_Payload()
}

type C2SMessage_Move struct {
	Move *MoveInput `protobuf:"bytes,1,opt,name=move,proto3,oneof"`
}

type C2SMessage_UseItem struct {
	UseItem *UseItemInput `protobuf:"bytes,2,opt,name=use_item,json=useItem,proto3,oneof"`
}

type C2SMessage_Interact struct {
	Interact bool `protobuf:"varint,3,opt,name=interact,proto3,oneof"`
}

type C2SMessage_Pickup struct {
	Pickup bool `protobuf:"varint,4,opt,name=pickup,proto3,oneof"`
}

type C2SMessage_Drop struct {
	Drop *DropInput `protobuf:"bytes,5,opt,name=drop,proto3,oneof"`
}

type C2SMessage_Tactic struct {
	Tactic *TacticInput `protobuf:"bytes,6,opt,name=tactic,proto3,oneof"`
}

type C2SMessage_Buy struct {
	Buy *BuyInput `protobuf:"bytes,7,opt,name=buy,proto3,oneof"`
}

type C2SMessage_Sell struct {
	Sell *SellInput `protobuf:"bytes,8,opt,name=sell,proto3,oneof"`
}

type C2SMessage_ShopRefresh struct {
	ShopRefresh bool `protobuf:"varint,9,opt,name=shop_refresh,json=shopRefresh,proto3,oneof"`
}

type C2SMessage_Fire struct {
	Fire bool `protobuf:"varint,10,opt,name=fire,proto3,oneof"`
}

type C2SMessage_DevSkip struct {
	DevSkip bool `protobuf:"varint,99,opt,name=dev_skip,json=devSkip,proto3,oneof"`
}

func (*C2SMessage_Move) isC2SMessage_Payload() {}

func (*C2SMessage_UseItem) isC2SMessage_Payload() {}

func (*C2SMessage_Interact) isC2SMessage_Payload() {}

func (*C2SMessage_Pickup) isC2SMessage_Payload() {}

func (*C2SMessage_Drop) isC2SMessage_Payload() {}

func (*C2SMessage_Tactic) isC2SMessage_Payload() {}

func (*C2SMessage_Buy) isC2SMessage_Payload() {}

func (*C2SMessage_Sell) isC2SMessage_Payload() {}

func (*C2SMessage_ShopRefresh) isC2SMessage_Payload() {}

func (*C2SMessage_Fire) isC2SMessage_Payload() {}

func (*C2SMessage_DevSkip) isC2SMessage_Payload() {}

type EntitySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Pos           *Vector2               `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
	State         int32                  `protobuf:"varint,4,opt,name=state,proto3" json:"state,omitempty"`
	Extra         []byte                 `protobuf:"bytes,5,opt,name=extra,proto3" json:"extra,omitempty"` // Serialized type-specific data (Motor/Supply/Projectile/AI)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntitySnapshot) Reset() {
	*x = EntitySnapshot{}
	mi := &file_proto_echo_trace_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitySnapshot) ProtoMessage() {}

func (x *EntitySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitySnapshot.ProtoReflect.Descriptor instead.
func (*EntitySnapshot) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{9}
}

func (x *EntitySnapshot) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *EntitySnapshot) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EntitySnapshot) GetPos() *Vector2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *EntitySnapshot) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *EntitySnapshot) GetExtra() []byte {
	if x != nil {
		return x.Extra
	}
	return nil
}

type PlayerSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pos           *Vector2               `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
	LookDir       *Vector2               `protobuf:"bytes,4,opt,name=look_dir,json=lookDir,proto3" json:"look_dir,omitempty"`
	Hp            float64                `protobuf:"fixed64,5,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         float64                `protobuf:"fixed64,6,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Armor         float64                `protobuf:"fixed64,7,opt,name=armor,proto3" json:"armor,omitempty"`
	MaxArmor      float64                `protobuf:"fixed64,8,opt,name=max_armor,json=maxArmor,proto3" json:"max_armor,omitempty"`
	Kills         int32                  `protobuf:"varint,9,opt,name=kills,proto3" json:"kills,omitempty"`
	IsAlive       bool                   `protobuf:"varint,10,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	Inventory     []*Item                `protobuf:"bytes,11,rep,name=inventory,proto3" json:"inventory,omitempty"`
	Funds         int32                  `protobuf:"varint,12,opt,name=funds,proto3" json:"funds,omitempty"`
	ClientMsg     string                 `protobuf:"bytes,13,opt,name=client_msg,json=clientMsg,proto3" json:"client_msg,omitempty"`
	AmmoType      string                 `protobuf:"bytes,14,opt,name=ammo_type,json=ammoType,proto3" json:"ammo_type,omitempty"`
	AmmoCount     int32                  `protobuf:"varint,15,opt,name=ammo_count,json=ammoCount,proto3" json:"ammo_count,omitempty"`
	InventoryCap  int32                  `protobuf:"varint,16,opt,name=inventory_cap,json=inventoryCap,proto3" json:"inventory_cap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSnapshot) Reset() {
	*x = PlayerSnapshot{}
	mi := &file_proto_echo_trace_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSnapshot) ProtoMessage() {}

func (x *PlayerSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSnapshot.ProtoReflect.Descriptor instead.
func (*PlayerSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{10}
}

func (x *PlayerSnapshot) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PlayerSnapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerSnapshot) GetPos() *Vector2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *PlayerSnapshot) GetLookDir() *Vector2 {
	if x != nil {
		return x.LookDir
	}
	return nil
}

func (x *PlayerSnapshot) GetHp() float64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *PlayerSnapshot) GetMaxHp() float64 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *PlayerSnapshot) GetArmor() float64 {
	if x != nil {
		return x.Armor
	}
	return 0
}

func (x *PlayerSnapshot) GetMaxArmor() float64 {
	if x != nil {
		return x.MaxArmor
	}
	return 0
}

func (x *PlayerSnapshot) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerSnapshot) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *PlayerSnapshot) GetInventory() []*Item {
	if x != nil {
		return x.Inventory
	}
	return nil
}

func (x *PlayerSnapshot) GetFunds() int32 {
	if x != nil {
		return x.Funds
	}
	return 0
}

func (x *PlayerSnapshot) GetClientMsg() string {
	if x != nil {
		return x.ClientMsg
	}
	return ""
}

func (x *PlayerSnapshot) GetAmmoType() string {
	if x != nil {
		return x.AmmoType
	}
	return ""
}

func (x *PlayerSnapshot) GetAmmoCount() int32 {
	if x != nil {
		return x.AmmoCount
	}
	return 0
}

func (x *PlayerSnapshot) GetInventoryCap() int32 {
	if x != nil {
		return x.InventoryCap
	}
	return 0
}

type RadarBlip struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Pos           *Vector2               `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RadarBlip) Reset() {
	*x = RadarBlip{}
	mi := &file_proto_echo_trace_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadarBlip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadarBlip) ProtoMessage() {}

func (x *RadarBlip) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadarBlip.ProtoReflect.Descriptor instead.
func (*RadarBlip) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{11}
}

func (x *RadarBlip) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RadarBlip) GetPos() *Vector2 {
	if x != nil {
		return x.Pos
	}
	return nil
}

type GameEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameEvent) Reset() {
	*x = GameEvent{}
	mi := &file_proto_echo_trace_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEvent) ProtoMessage() {}

func (x *GameEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEvent.ProtoReflect.Descriptor instead.
func (*GameEvent) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{12}
}

func (x *GameEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GameEvent) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// Full state snapshot (sent per player per tick)
type StateSnapshot struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Phase        int32                  `protobuf:"varint,1,opt,name=phase,proto3" json:"phase,omitempty"`
	TimeLeft     float64                `protobuf:"fixed64,2,opt,name=time_left,json=timeLeft,proto3" json:"time_left,omitempty"`
	TotalKills   int32                  `protobuf:"varint,3,opt,name=total_kills,json=totalKills,proto3" json:"total_kills,omitempty"`
	JammerActive bool                   `protobuf:"varint,4,opt,name=jammer_active,json=jammerActive,proto3" json:"jammer_active,omitempty"`
	// My state
	MyState *PlayerSnapshot `protobuf:"bytes,5,opt,name=my_state,json=myState,proto3" json:"my_state,omitempty"`
	// Other players (visible)
	OtherPlayers []*PlayerSnapshot `protobuf:"bytes,6,rep,name=other_players,json=otherPlayers,proto3" json:"other_players,omitempty"`
	// Entities
	Entities []*EntitySnapshot `protobuf:"bytes,7,rep,name=entities,proto3" json:"entities,omitempty"`
	// Radar
	RadarBlips []*RadarBlip `protobuf:"bytes,8,rep,name=radar_blips,json=radarBlips,proto3" json:"radar_blips,omitempty"`
	// Events (ring buffer, last 5)
	Events []*GameEvent `protobuf:"bytes,9,rep,name=events,proto3" json:"events,omitempty"`
	// Shop (if near merchant)
	ShopStock     []string `protobuf:"bytes,10,rep,name=shop_stock,json=shopStock,proto3" json:"shop_stock,omitempty"`
	ShopPrices    []int32  `protobuf:"varint,11,rep,packed,name=shop_prices,json=shopPrices,proto3" json:"shop_prices,omitempty"`
	ShopTypes     []string `protobuf:"bytes,12,rep,name=shop_types,json=shopTypes,proto3" json:"shop_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSnapshot) Reset() {
	*x = StateSnapshot{}
	mi := &file_proto_echo_trace_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshot) ProtoMessage() {}

func (x *StateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshot.ProtoReflect.Descriptor instead.
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{13}
}

func (x *StateSnapshot) GetPhase() int32 {
	if x != nil {
		return x.Phase
	}
	return 0
}

func (x *StateSnapshot) GetTimeLeft() float64 {
	if x != nil {
		return x.TimeLeft
	}
	return 0
}

func (x *StateSnapshot) GetTotalKills() int32 {
	if x != nil {
		return x.TotalKills
	}
	return 0
}

func (x *StateSnapshot) GetJammerActive() bool {
	if x != nil {
		return x.JammerActive
	}
	return false
}

func (x *StateSnapshot) GetMyState() *PlayerSnapshot {
	if x != nil {
		return x.MyState
	}
	return nil
}

func (x *StateSnapshot) GetOtherPlayers() []*PlayerSnapshot {
	if x != nil {
		return x.OtherPlayers
	}
	return nil
}

func (x *StateSnapshot) GetEntities() []*EntitySnapshot {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *StateSnapshot) GetRadarBlips() []*RadarBlip {
	if x != nil {
		return x.RadarBlips
	}
	return nil
}

func (x *StateSnapshot) GetEvents() []*GameEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *StateSnapshot) GetShopStock() []string {
	if x != nil {
		return x.ShopStock
	}
	return nil
}

func (x *StateSnapshot) GetShopPrices() []int32 {
	if x != nil {
		return x.ShopPrices
	}
	return nil
}

func (x *StateSnapshot) GetShopTypes() []string {
	if x != nil {
		return x.ShopTypes
	}
	return nil
}

// Map data (sent once at game start)
type MapData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Tiles         []int32                `protobuf:"varint,3,rep,packed,name=tiles,proto3" json:"tiles,omitempty"` // Flattened row-major array
	SpawnPos      *Vector2               `protobuf:"bytes,4,opt,name=spawn_pos,json=spawnPos,proto3" json:"spawn_pos,omitempty"`
	Inventory     []*Item                `protobuf:"bytes,5,rep,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapData) Reset() {
	*x = MapData{}
	mi := &file_proto_echo_trace_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapData) ProtoMessage() {}

func (x *MapData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapData.ProtoReflect.Descriptor instead.
func (*MapData) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{14}
}

func (x *MapData) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MapData) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MapData) GetTiles() []int32 {
	if x != nil {
		return x.Tiles
	}
	return nil
}

func (x *MapData) GetSpawnPos() *Vector2 {
	if x != nil {
		return x.SpawnPos
	}
	return nil
}

func (x *MapData) GetInventory() []*Item {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type S2CMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*S2CMessage_Snapshot
	//	*S2CMessage_MapData
	Payload       isS2CMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *S2CMessage) Reset() {
	*x = S2CMessage{}
	mi := &file_proto_echo_trace_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *S2CMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*S2CMessage) ProtoMessage() {}

func (x *S2CMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use S2CMessage.ProtoReflect.Descriptor instead.
func (*S2CMessage) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{15}
}

func (x *S2CMessage) GetPayload() isS2CMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *S2CMessage) GetSnapshot() *StateSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*S2CMessage_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *S2CMessage) GetMapData() *MapData {
	if x != nil {
		if x, ok := x.Payload.(*S2CMessage_MapData); ok {
			return x.MapData
		}
	}
	return nil
}

type isS2CMessage_Payload interface {
	isS2CMessage_Payload()
}

type S2CMessage_Snapshot struct {
	Snapshot *StateSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type S2CMessage_MapData struct {
	MapData *MapData `protobuf:"bytes,2,opt,name=map_data,json=mapData,proto3,oneof"`
}

func (*S2CMessage_Snapshot) isS2CMessage_Payload() {}

func (*S2CMessage_MapData) isS2CMessage_Payload() {}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`      // Message type code (matches legacy protocol.json)
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // Serialized C2SMessage or S2CMessage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_echo_trace_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echo_trace_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_echo_trace_proto_rawDescGZIP(), []int{16}
}

func (x *Envelope) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_echo_trace_proto protoreflect.FileDescriptor

const file_proto_echo_trace_proto_rawDesc = "" +
	"\n" +
	"\x16proto/echo_trace.proto\x12\n" +
	"echo_trace\"%\n" +
	"\aVector2\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\xb8\x01\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x19\n" +
	"\bmax_uses\x18\x04 \x01(\x05R\amaxUses\x12\x1b\n" +
	"\tuses_left\x18\x05 \x01(\x05R\busesLeft\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x01R\x06weight\x12\x12\n" +
	"\x04tier\x18\a \x01(\x05R\x04tier\x12\x14\n" +
	"\x05value\x18\b \x01(\x05R\x05value\"\x84\x01\n" +
	"\tMoveInput\x12%\n" +
	"\x03dir\x18\x01 \x01(\v2\x13.echo_trace.Vector2R\x03dir\x12.\n" +
	"\blook_dir\x18\x02 \x01(\v2\x13.echo_trace.Vector2R\alookDir\x12 \n" +
	"\fhas_look_dir\x18\x03 \x01(\bR\n" +
	"hasLookDir\"-\n" +
	"\fUseItemInput\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x01 \x01(\x05R\tslotIndex\"*\n" +
	"\tDropInput\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x01 \x01(\x05R\tslotIndex\"#\n" +
	"\bBuyInput\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"*\n" +
	"\tSellInput\x12\x1d\n" +
	"\n" +
	"slot_index\x18\x01 \x01(\x05R\tslotIndex\"%\n" +
	"\vTacticInput\x12\x16\n" +
	"\x06tactic\x18\x01 \x01(\tR\x06tactic\"\xc2\x03\n" +
	"\n" +
	"C2SMessage\x12+\n" +
	"\x04move\x18\x01 \x01(\v2\x15.echo_trace.MoveInputH\x00R\x04move\x125\n" +
	"\buse_item\x18\x02 \x01(\v2\x18.echo_trace.UseItemInputH\x00R\auseItem\x12\x1c\n" +
	"\binteract\x18\x03 \x01(\bH\x00R\binteract\x12\x18\n" +
	"\x06pickup\x18\x04 \x01(\bH\x00R\x06pickup\x12+\n" +
	"\x04drop\x18\x05 \x01(\v2\x15.echo_trace.DropInputH\x00R\x04drop\x121\n" +
	"\x06tactic\x18\x06 \x01(\v2\x17.echo_trace.TacticInputH\x00R\x06tactic\x12(\n" +
	"\x03buy\x18\a \x01(\v2\x14.echo_trace.BuyInputH\x00R\x03buy\x12+\n" +
	"\x04sell\x18\b \x01(\v2\x15.echo_trace.SellInputH\x00R\x04sell\x12#\n" +
	"\fshop_refresh\x18\t \x01(\bH\x00R\vshopRefresh\x12\x14\n" +
	"\x04fire\x18\n" +
	" \x01(\bH\x00R\x04fire\x12\x1b\n" +
	"\bdev_skip\x18c \x01(\bH\x00R\adevSkipB\t\n" +
	"\apayload\"\x89\x01\n" +
	"\x0eEntitySnapshot\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12%\n" +
	"\x03pos\x18\x03 \x01(\v2\x13.echo_trace.Vector2R\x03pos\x12\x14\n" +
	"\x05state\x18\x04 \x01(\x05R\x05state\x12\x14\n" +
	"\x05extra\x18\x05 \x01(\fR\x05extra\"\xeb\x03\n" +
	"\x0ePlayerSnapshot\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x03pos\x18\x03 \x01(\v2\x13.echo_trace.Vector2R\x03pos\x12.\n" +
	"\blook_dir\x18\x04 \x01(\v2\x13.echo_trace.Vector2R\alookDir\x12\x0e\n" +
	"\x02hp\x18\x05 \x01(\x01R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x06 \x01(\x01R\x05maxHp\x12\x14\n" +
	"\x05armor\x18\a \x01(\x01R\x05armor\x12\x1b\n" +
	"\tmax_armor\x18\b \x01(\x01R\bmaxArmor\x12\x14\n" +
	"\x05kills\x18\t \x01(\x05R\x05kills\x12\x19\n" +
	"\bis_alive\x18\n" +
	" \x01(\bR\aisAlive\x12.\n" +
	"\tinventory\x18\v \x03(\v2\x10.echo_trace.ItemR\tinventory\x12\x14\n" +
	"\x05funds\x18\f \x01(\x05R\x05funds\x12\x1d\n" +
	"\n" +
	"client_msg\x18\r \x01(\tR\tclientMsg\x12\x1b\n" +
	"\tammo_type\x18\x0e \x01(\tR\bammoType\x12\x1d\n" +
	"\n" +
	"ammo_count\x18\x0f \x01(\x05R\tammoCount\x12#\n" +
	"\rinventory_cap\x18\x10 \x01(\x05R\finventoryCap\"F\n" +
	"\tRadarBlip\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12%\n" +
	"\x03pos\x18\x02 \x01(\v2\x13.echo_trace.Vector2R\x03pos\"1\n" +
	"\tGameEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\xfe\x03\n" +
	"\rStateSnapshot\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\x05R\x05phase\x12\x1b\n" +
	"\ttime_left\x18\x02 \x01(\x01R\btimeLeft\x12\x1f\n" +
	"\vtotal_kills\x18\x03 \x01(\x05R\n" +
	"totalKills\x12#\n" +
	"\rjammer_active\x18\x04 \x01(\bR\fjammerActive\x125\n" +
	"\bmy_state\x18\x05 \x01(\v2\x1a.echo_trace.PlayerSnapshotR\amyState\x12?\n" +
	"\rother_players\x18\x06 \x03(\v2\x1a.echo_trace.PlayerSnapshotR\fotherPlayers\x126\n" +
	"\bentities\x18\a \x03(\v2\x1a.echo_trace.EntitySnapshotR\bentities\x126\n" +
	"\vradar_blips\x18\b \x03(\v2\x15.echo_trace.RadarBlipR\n" +
	"radarBlips\x12-\n" +
	"\x06events\x18\t \x03(\v2\x15.echo_trace.GameEventR\x06events\x12\x1d\n" +
	"\n" +
	"shop_stock\x18\n" +
	" \x03(\tR\tshopStock\x12\x1f\n" +
	"\vshop_prices\x18\v \x03(\x05R\n" +
	"shopPrices\x12\x1d\n" +
	"\n" +
	"shop_types\x18\f \x03(\tR\tshopTypes\"\xaf\x01\n" +
	"\aMapData\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x14\n" +
	"\x05tiles\x18\x03 \x03(\x05R\x05tiles\x120\n" +
	"\tspawn_pos\x18\x04 \x01(\v2\x13.echo_trace.Vector2R\bspawnPos\x12.\n" +
	"\tinventory\x18\x05 \x03(\v2\x10.echo_trace.ItemR\tinventory\"\x82\x01\n" +
	"\n" +
	"S2CMessage\x127\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x19.echo_trace.StateSnapshotH\x00R\bsnapshot\x120\n" +
	"\bmap_data\x18\x02 \x01(\v2\x13.echo_trace.MapDataH\x00R\amapDataB\t\n" +
	"\apayload\"8\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayloadB\x19Z\x17echo_trace_server/protob\x06proto3"

var (
	file_proto_echo_trace_proto_rawDescOnce sync.Once
	file_proto_echo_trace_proto_rawDescData []byte
)

func file_proto_echo_trace_proto_rawDescGZIP() []byte {
	file_proto_echo_trace_proto_rawDescOnce.Do(func() {
		file_proto_echo_trace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_echo_trace_proto_rawDesc), len(file_proto_echo_trace_proto_rawDesc)))
	})
	return file_proto_echo_trace_proto_rawDescData
}

var file_proto_echo_trace_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_echo_trace_proto_goTypes = []any{
	(*Vector2)(nil),        // 0: echo_trace.Vector2
	(*Item)(nil),           // 1: echo_trace.Item
	(*MoveInput)(nil),      // 2: echo_trace.MoveInput
	(*UseItemInput)(nil),   // 3: echo_trace.UseItemInput
	(*DropInput)(nil),      // 4: echo_trace.DropInput
	(*BuyInput)(nil),       // 5: echo_trace.BuyInput
	(*SellInput)(nil),      // 6: echo_trace.SellInput
	(*TacticInput)(nil),    // 7: echo_trace.TacticInput
	(*C2SMessage)(nil),     // 8: echo_trace.C2SMessage
	(*EntitySnapshot)(nil), // 9: echo_trace.EntitySnapshot
	(*PlayerSnapshot)(nil), // 10: echo_trace.PlayerSnapshot
	(*RadarBlip)(nil),      // 11: echo_trace.RadarBlip
	(*GameEvent)(nil),      // 12: echo_trace.GameEvent
	(*StateSnapshot)(nil),  // 13: echo_trace.StateSnapshot
	(*MapData)(nil),        // 14: echo_trace.MapData
	(*S2CMessage)(nil),     // 15: echo_trace.S2CMessage
	(*Envelope)(nil),       // 16: echo_trace.Envelope
}
var file_proto_echo_trace_proto_depIdxs = []int32{
	0,  // 0: echo_trace.MoveInput.dir:type_name -> echo_trace.Vector2
	0,  // 1: echo_trace.MoveInput.look_dir:type_name -> echo_trace.Vector2
	2,  // 2: echo_trace.C2SMessage.move:type_name -> echo_trace.MoveInput
	3,  // 3: echo_trace.C2SMessage.use_item:type_name -> echo_trace.UseItemInput
	4,  // 4: echo_trace.C2SMessage.drop:type_name -> echo_trace.DropInput
	7,  // 5: echo_trace.C2SMessage.tactic:type_name -> echo_trace.TacticInput
	5,  // 6: echo_trace.C2SMessage.buy:type_name -> echo_trace.BuyInput
	6,  // 7: echo_trace.C2SMessage.sell:type_name -> echo_trace.SellInput
	0,  // 8: echo_trace.EntitySnapshot.pos:type_name -> echo_trace.Vector2
	0,  // 9: echo_trace.PlayerSnapshot.pos:type_name -> echo_trace.Vector2
	0,  // 10: echo_trace.PlayerSnapshot.look_dir:type_name -> echo_trace.Vector2
	1,  // 11: echo_trace.PlayerSnapshot.inventory:type_name -> echo_trace.Item
	0,  // 12: echo_trace.RadarBlip.pos:type_name -> echo_trace.Vector2
	10, // 13: echo_trace.StateSnapshot.my_state:type_name -> echo_trace.PlayerSnapshot
	10, // 14: echo_trace.StateSnapshot.other_players:type_name -> echo_trace.PlayerSnapshot
	9,  // 15: echo_trace.StateSnapshot.entities:type_name -> echo_trace.EntitySnapshot
	11, // 16: echo_trace.StateSnapshot.radar_blips:type_name -> echo_trace.RadarBlip
	12, // 17: echo_trace.StateSnapshot.events:type_name -> echo_trace.GameEvent
	0,  // 18: echo_trace.MapData.spawn_pos:type_name -> echo_trace.Vector2
	1,  // 19: echo_trace.MapData.inventory:type_name -> echo_trace.Item
	13, // 20: echo_trace.S2CMessage.snapshot:type_name -> echo_trace.StateSnapshot
	14, // 21: echo_trace.S2CMessage.map_data:type_name -> echo_trace.MapData
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_echo_trace_proto_init() }
func file_proto_echo_trace_proto_init() {
	if File_proto_echo_trace_proto != nil {
		return
	}
	file_proto_echo_trace_proto_msgTypes[8].OneofWrappers = []any{
		(*C2SMessage_Move)(nil),
		(*C2SMessage_UseItem)(nil),
		(*C2SMessage_Interact)(nil),
		(*C2SMessage_Pickup)(nil),
		(*C2SMessage_Drop)(nil),
		(*C2SMessage_Tactic)(nil),
		(*C2SMessage_Buy)(nil),
		(*C2SMessage_Sell)(nil),
		(*C2SMessage_ShopRefresh)(nil),
		(*C2SMessage_Fire)(nil),
		(*C2SMessage_DevSkip)(nil),
	}
	file_proto_echo_trace_proto_msgTypes[15].OneofWrappers = []any{
		(*S2CMessage_Snapshot)(nil),
		(*S2CMessage_MapData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_echo_trace_proto_rawDesc), len(file_proto_echo_trace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_echo_trace_proto_goTypes,
		DependencyIndexes: file_proto_echo_trace_proto_depIdxs,
		MessageInfos:      file_proto_echo_trace_proto_msgTypes,
	}.Build()
	File_proto_echo_trace_proto = out.File
	file_proto_echo_trace_proto_goTypes = nil
	file_proto_echo_trace_proto_depIdxs = nil
}
